[package]
name = "solana-paux-escrow"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "1.7.11"
thiserror = "1.0.29"

[dev-dependencies]
solana-sdk = "1.7.11"

[lib]
crate-type = ["cdylib", "lib"]
